// AUTO_GENERATED by JavaPoet
package JavaPoet;

import java.lang.String;
import java.lang.System;
import java.time.LocalDateTime;

public class FlightMsg {
  private final int aircraftId;

  private final String departure;

  /**
   * Time of departure will be set via tower confirmation
   */
  private LocalDateTime timeOfDeparture;

  public FlightMsg(final int aircraftId, final String departure) {
    this.aircraftId = aircraftId;
    this.departure = departure;
  }

  public int getAircraftId() {
    return aircraftId;
  }

  public String getDeparture() {
    return departure;
  }

  public LocalDateTime takeOffConfirmed() {
    this.timeOfDeparture = LocalDateTime.now();
    System.out.println("Tower has confirmed takeoff");
    return timeOfDeparture;
  }
}
